# Generated by Django 6.1.1 on 2026-10-05 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва кафедри')),
                ('head_name', models.CharField(max_length=150, verbose_name='Завідувач кафедри')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Факультет економічних наук', max_length=200, verbose_name='Назва факультету')),
                ('description', models.TextField(verbose_name='Опис Факультету')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Інформація головної сторінки',
                'verbose_name_plural': 'Інформація головної сторінки',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=200, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Опис спеціальності')),
                ('coordinator_name', models.CharField(max_length=150, verbose_name="Ім'я координатора набору")),
                ('coordinator_contact', models.CharField(max_length=100, verbose_name='Контакт координатора')),
                ('courses', models.TextField(blank=True, verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduating_specialties', to='faculty_site.department', verbose_name='Випускова кафедра')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я викладача")),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('degree', models.CharField(max_length=100, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='faculty_site.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
    ]
