# Generated by Django 6.1.1 on 2026-10-06 00:02

from django.db import migrations, models

def split_university_data(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty_site', 'ExchangeProgram')
    for prog in ExchangeProgram.objects.all():
        raw = prog.university.strip()
        # У таблиці країна відокремлена по-різному: комою, " - " або дужками
        if ',' in raw:
            name, country = raw.split(',', 1)
        elif ' - ' in raw:
            name, country = raw.split(' - ', 1)
        elif '(' in raw and raw.endswith(')'):
            name, country = raw[:-1].split('(', 1)
        else:
            name, country = raw, 'Невідомо'
        prog.university_name = name.strip()
        prog.country = country.strip()
        prog.save(update_fields=['university_name', 'country'])

def merge_university_data(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty_site', 'ExchangeProgram')
    for prog in ExchangeProgram.objects.all():
        prog.university = f"{prog.university_name}, {prog.country}"
        prog.save(update_fields=['university'])

class Migration(migrations.Migration):

    dependencies = [
        ('faculty_site', '0003_seed_exchange_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(default='', max_length=200, verbose_name='Назва університету'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Країна'),
            preserve_default=False,
        ),
        migrations.RunPython(split_university_data, reverse_code=merge_university_data),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university',
            field=models.TextField(default='', verbose_name='Університет'),
        ),
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='university',
        ),
    ]
